version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY
      - STEAM_KEY
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db